export const catsData = [
  {
    emotionTags: ["moody"],
    isGif: false,
    image: "angry.jpeg",
    alt: "A cat looking moody",
  },
  {
    emotionTags: ["moody", "insomniac"],
    isGif: false,
    image: "angry2.jpeg",
    alt: "A cat looking moody",
  },
  {
    emotionTags: ["moody"],
    isGif: false,
    image: "angry3.jpeg",
    alt: "A cat looking moody",
  },
  {
    emotionTags: ["confused", "sad"],
    isGif: false,
    image: "confused.jpeg",
    alt: "A cat looking confused",
  },
  {
    emotionTags: ["dominant", "moody"],
    isGif: false,
    image: "dominant.jpeg",
    alt: "A cat looking dominant",
  },
  {
    emotionTags: ["happy", "relaxed"],
    isGif: false,
    image: "happy.jpeg",
    alt: "A cat looking happy",
  },
  {
    emotionTags: ["hungry"],
    isGif: false,
    image: "hungry.jpeg",
    alt: "A cat looking hungry",
  },
  {
    emotionTags: ["hungry"],
    isGif: false,
    image: "hungry1.jpeg",
    alt: "A cat looking hungry",
  },
  {
    emotionTags: ["insomniac"],
    isGif: false,
    image: "insomnia.jpeg",
    alt: "A cat looking insomniac",
  },
  {
    emotionTags: ["insomniac"],
    isGif: false,
    image: "insomnia1.jpeg",
    alt: "A cat looking insomniac",
  },
  {
    emotionTags: ["relaxed"],
    isGif: false,
    image: "lazy.jpeg",
    alt: "A cat looking lazy",
  },
  {
    emotionTags: ["scared"],
    isGif: false,
    image: "nervous.jpeg",
    alt: "A cat looking nervous",
  },
  {
    emotionTags: ["sad"],
    isGif: false,
    image: "sad.jpeg",
    alt: "A cat looking sad",
  },
  {
    emotionTags: ["sad", "moody"],
    isGif: false,
    image: "sad1.jpeg",
    alt: "A cat looking sad",
  },
  {
    emotionTags: ["moody"],
    isGif: true,
    image: "angry.gif",
    alt: "A cat looking moody",
  },
  {
    emotionTags: ["moody"],
    isGif: true,
    image: "angry2.gif",
    alt: "A cat looking angry",
  },
  {
    emotionTags: ["confused"],
    isGif: true,
    image: "confused2.gif",
    alt: "A cat looking confused",
  },
  {
    emotionTags: ["dominant"],
    isGif: true,
    image: "dominant.gif",
    alt: "A cat looking dominant",
  },
  {
    emotionTags: ["happy"],
    isGif: true,
    image: "happy.gif",
    alt: "A cat looking happy",
  },
  {
    emotionTags: ["hungry", "sad", "confused"],
    isGif: true,
    image: "confused.gif",
    alt: "A cat looking hungry",
  },
  {
    emotionTags: ["hungry"],
    isGif: true,
    image: "hungry.gif",
    alt: "A cat looking hungry",
  },
  {
    emotionTags: ["hungry"],
    isGif: true,
    image: "hungry2.gif",
    alt: "A cat looking hungry",
  },
  {
    emotionTags: ["insomniac", "scared"],
    isGif: true,
    image: "insomnia2.gif",
    alt: "A cat looking insomniac",
  },
  {
    emotionTags: ["relaxed"],
    isGif: true,
    image: "lazy.gif",
    alt: "A cat looking relaxed",
  },
  {
    emotionTags: ["relaxed"],
    isGif: true,
    image: "relaxed2.gif",
    alt: "A cat looking relaxed",
  },
  {
    emotionTags: ["scared", "sad"],
    isGif: true,
    image: "nervous.gif",
    alt: "A cat looking nervous",
  },
  {
    emotionTags: ["scared"],
    isGif: true,
    image: "nervous2.gif",
    alt: "A cat looking scared",
  },
  {
    emotionTags: ["sad"],
    isGif: true,
    image: "sad.gif",
    alt: "A cat looking sad",
  },
];

export const catCategories = [
  "happy",
  "sad",
  "box",
  "angry",
  "hungry",
  "fat",
  "excited",
  "scared",
  "relaxed",
  "confused",
  "moody",
];
export const catEmotions = [
  "#christmascat",
  "#scottishfold",
  "2cats",
  "4",
  "@Beardlyness",
  "Beer",
  "Belfast",
  "BelfastMet",
  "Black",
  "Box",
  "Buckley",
  "Cat",
  "Cat in a faucet",
  "Catto",
  "Chair",
  "Christmas",
  "CryptoWorld Cat",
  "Curious",
  "Cute",
  "Dark",
  "FAT",
  "Female",
  "Friends",
  "Fulgencio",
  "Going shopping?",
  "Grumpy",
  "Hiding",
  "Lay",
  "Luz",
  "Maine Coon",
  "Male",
  "Maskcat",
  "Mimi",
  "My cat(Mamay(мамай)) bebrik.xyz",
  "NSFW",
  "Norwegian",
  "Norwegian Forest Cat",
  "Orange",
  "Outside",
  "Quantico",
  "Ragdoll",
  "Relaxed",
  "Roar",
  "Sad",
  "Scout",
  "Shhhsh",
  "Sleepy",
  "Sniper",
  "Summer",
  "Tabby",
  "Tassilo",
  "Teeth",
  "Tired cat",
  "TorWorld Cat",
  "Torte",
  "Torte Tabby",
  "Trippy",
  "Weegie",
  "Wet",
  "White",
  "X-MAS",
  "Yeet",
  "advent-calendar-2016",
  "afraid",
  "alcoholic",
  "alien",
  "ange",
  "angel",
  "angry",
  "angry cat",
  "annilou91",
  "anoyed",
  "anstrengend",
  "approaching",
  "artist",
  "asking",
  "attack",
  "attention",
  "attitude",
  "ava",
  "baby",
  "background",
  "bamgu",
  "banker",
  "banzai",
  "basin",
  "basket",
  "bath",
  "beautiful",
  "bed",
  "beer",
  "beg",
  "begging",
  "belly",
  "belly rubs",
  "bengal",
  "big",
  "big eyes",
  "big-eyes",
  "bigfloppa",
  "bird",
  "biscuit",
  "black",
  "black & white",
  "black an white",
  "black and white",
  "black cat",
  "blanket",
  "blep",
  "blini",
  "blue",
  "blur",
  "blurred",
  "bombay",
  "boot",
  "box",
  "boxe",
  "brasileira",
  "brazilian",
  "brazilian cat",
  "bread",
  "british shorthair",
  "british-shorthair",
  "brown",
  "bubble",
  "bucket",
  "bun",
  "burrito",
  "burrito-cat",
  "bw",
  "cake",
  "calico",
  "calvin",
  "candle",
  "car",
  "caracal",
  "cash",
  "cat",
  "cat eyes",
  "cat face",
  "cat kneading",
  "cat meowing",
  "cat on table",
  "cat wallpaper",
  "cat_winston",
  "cats",
  "catto",
  "chair",
  "chaos",
  "check",
  "chonker",
  "christmas",
  "clawing",
  "climb",
  "close",
  "closed eyes",
  "closeup",
  "clothes",
  "coat",
  "color",
  "colorful",
  "comfy",
  "computer",
  "confused",
  "cooking",
  "cool",
  "costume",
  "couch",
  "cow",
  "cowboy",
  "crazy",
  "crazy russian pussycat",
  "creation",
  "crying",
  "cryptid",
  "cucumber",
  "cuddle",
  "cuddles",
  "cup",
  "curl",
  "cut",
  "cute",
  "cute cat",
  "cutie",
  "daisy",
  "dance",
  "dark",
  "dark vador",
  "darth",
  "darth vader",
  "davie412",
  "dead",
  "derp",
  "detective",
  "dev",
  "devcat",
  "dictator",
  "didizin",
  "dinner!",
  "disappointed",
  "dj",
  "dogstyle",
  "donna",
  "double",
  "down",
  "dream",
  "drink",
  "drone",
  "drugs",
  "drunk",
  "dumb",
  "duo",
  "ears",
  "ears back",
  "engineer",
  "evil",
  "excited",
  "exferal",
  "eye",
  "eyes",
  "facecat",
  "fail",
  "fall",
  "fat",
  "fat cat",
  "faucet",
  "fedora",
  "felix",
  "fell",
  "female",
  "female cat",
  "fight",
  "file",
  "fire",
  "floof",
  "floor",
  "floppa",
  "flowers",
  "fluffy",
  "flying",
  "focused",
  "fold",
  "food",
  "food dish",
  "forest cat",
  "fotel",
  "freeze",
  "fridge",
  "friends",
  "front_view",
  "fun",
  "funn",
  "funny",
  "funny kitty",
  "furious",
  "gamer",
  "gaming",
  "gg",
  "gif",
  "ginger",
  "ginger cat",
  "glass",
  "glow",
  "goodness_gracious",
  "goofy",
  "grass",
  "gray",
  "green eyes",
  "grooming",
  "group",
  "grump",
  "grumpy",
  "guilty",
  "gun",
  "gutter",
  "halloween",
  "happy",
  "hard",
  "hat",
  "head tilt",
  "headinacup",
  "headphones",
  "hedgehog",
  "held",
  "hello",
  "hi",
  "hide",
  "high_quality",
  "ho",
  "ho-wait",
  "hot",
  "hovercat",
  "hug",
  "huge",
  "hulu",
  "hunger",
  "hungry",
  "icecream",
  "if i fits i sits",
  "jade",
  "jellybean toes toe beans grey gray mauve",
  "jellybean toes toebeans squished beans",
  "jinx",
  "jojo",
  "judgemental",
  "judging",
  "jump",
  "jumping",
  "kick",
  "kiss",
  "kitler",
  "kitten",
  "kittenleg",
  "kittens",
  "kitty",
  "knocknoc",
  "kot",
  "kucing",
  "kuro",
  "laughing",
  "lay",
  "laying",
  "lazy fuck",
  "legs",
  "lick",
  "licking",
  "lights",
  "lila",
  "loaf",
  "logan",
  "lolcat",
  "londrina",
  "londrinense",
  "long",
  "long-cat",
  "looking",
  "looking at viewer",
  "loopy",
  "lustful",
  "lying down",
  "macCat",
  "mackerel tabby",
  "mad",
  "magnifier",
  "magnifying glass",
  "maine coon",
  "mama",
  "manspreading",
  "marine",
  "mask",
  "melon",
  "meme",
  "menacing",
  "meow",
  "metal",
  "mew",
  "misty",
  "mixed",
  "money",
  "moody",
  "morrigan",
  "morrigan witch of the wilds",
  "motion blur",
  "mousecat",
  "multi",
  "multiple_colors",
  "munchkin",
  "nasty",
  "needy",
  "nelly",
  "nelut",
  "newyear",
  "nicecat",
  "no",
  "nope",
  "norwegian forest cat",
  "nose",
  "nyancat",
  "nyancat-gif",
  "old",
  "omg",
  "ominous",
  "on back",
  "ooooo",
  "orange",
  "orange cat",
  "outside",
  "ovni",
  "pain",
  "pancakes",
  "party",
  "patoka",
  "paw",
  "pc",
  "pebba",
  "peppa",
  "pepper",
  "persian",
  "persian cat",
  "petting",
  "piano",
  "pic",
  "pillow",
  "pingu",
  "pino",
  "pippin",
  "play",
  "playful",
  "please",
  "pleasing",
  "plot",
  "plushie",
  "portrait-worthy",
  "praise",
  "pretty",
  "professional",
  "programmer",
  "psychedelic",
  "puffy",
  "quality",
  "qwerty",
  "radical",
  "rainbow",
  "reading",
  "red",
  "relaxing",
  "resting",
  "rich",
  "roll",
  "rolling",
  "running",
  "russia",
  "russian blue",
  "sad",
  "sad catto",
  "samurai",
  "sara",
  "sassy",
  "sauna cat",
  "savannah",
  "scared",
  "scream",
  "screm",
  "seeya!",
  "selfie",
  "serious",
  "several",
  "shark",
  "shirt",
  "shit",
  "shocked",
  "shoe",
  "siamese",
  "sideways",
  "silly",
  "sing",
  "sit",
  "sitting",
  "sitting up",
  "slap",
  "sleep",
  "sleeping",
  "sleepy",
  "sleepy cat",
  "slick",
  "slide",
  "slip",
  "slow motion",
  "smack",
  "small",
  "small cat",
  "smile",
  "smirk",
  "smol",
  "smug",
  "snow",
  "sock",
  "soda",
  "sofa",
  "soft",
  "some",
  "soon",
  "sound",
  "space",
  "spicy",
  "spin",
  "spooked",
  "spots",
  "square",
  "stack",
  "stair",
  "staline",
  "standing",
  "star wars",
  "stare",
  "staring",
  "startled",
  "stealing",
  "stick",
  "stip",
  "strange",
  "straw",
  "strawberry",
  "strech",
  "stretch",
  "stripes",
  "strong",
  "stuck",
  "stupid",
  "suicide",
  "summon",
  "sunglass",
  "sunglasses",
  "sunshi",
  "sunshibamgu",
  "supermodel",
  "surprised",
  "sushi",
  "swimming",
  "tabby",
  "table",
  "tair",
  "tech",
  "testdfsa",
  "they are coming",
  "thicc",
  "thief",
  "tinny",
  "tiny baby",
  "tired",
  "tofi",
  "tongue",
  "tortie",
  "tortoiseshell",
  "tortoiseshell cat",
  "toys",
  "transparent",
  "trapped",
  "tree",
  "triggered",
  "trump",
  "tryhard",
  "tryhard_cat",
  "turntable",
  "tux",
  "tuxedo",
  "tuxedo cat",
  "twitter",
  "two",
  "twocats",
  "twoface",
  "typing",
  "ugg",
  "ugly",
  "unhappy",
  "unicorn",
  "unit",
  "up",
  "up to 3kgs",
  "upset",
  "uwu",
  "v for vendetta",
  "vacuum",
  "vader",
  "vador",
  "vegetable",
  "vending machine",
  "victorious-cat",
  "victory",
  "waiting",
  "wakup",
  "walking",
  "water",
  "water balloon",
  "watter cat",
  "weinstein",
  "white",
  "white_fur",
  "why",
  "window",
  "witch",
  "worker",
  "workspace",
  "wtf",
  "xena",
  "yang",
  "yawn",
  "yawning",
  "yeay",
  "ying",
  "yoga",
  "zombie",
  "zusia",
  "なら",
];
